# Generated by Django 5.2.7 on 2025-10-16 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('laboratorio', models.CharField(blank=True, max_length=120)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No especificado')], default='X', max_length=1)),
                ('tipo_sangre', models.CharField(blank=True, choices=[('O+', 'O+'), ('O-', 'O-'), ('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=3)),
                ('correo', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medicos', to='clinica.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateTimeField()),
                ('motivo', models.CharField(max_length=200)),
                ('diagnostico', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('ATEN', 'Atendida'), ('CANC', 'Cancelada'), ('NOAS', 'No asiste')], default='PEND', max_length=4)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='clinica.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas', to='clinica.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='SeguroSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('plan', models.CharField(blank=True, max_length=120)),
            ],
            options={
                'unique_together': {('nombre', 'plan')},
            },
        ),
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('duracion_dias', models.PositiveIntegerField(default=0)),
                ('observaciones', models.TextField(blank=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos', to='clinica.consultamedica')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=60)),
                ('frecuencia', models.CharField(max_length=60)),
                ('duracion', models.CharField(max_length=60)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='clinica.medicamento')),
                ('tratamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='clinica.tratamiento')),
            ],
        ),
        migrations.CreateModel(
            name='PacienteSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_poliza', models.CharField(blank=True, max_length=60)),
                ('cobertura_porcentaje', models.PositiveIntegerField(default=0)),
                ('vigente', models.BooleanField(default=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguros', to='clinica.paciente')),
                ('seguro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='afiliados', to='clinica.segurosalud')),
            ],
            options={
                'unique_together': {('paciente', 'seguro')},
            },
        ),
    ]
